name: parse-pdf
channels:
  - defaults
  - conda-forge
  - fastai
dependencies:
  - pandas
  - pdftopng
  - ipykernel
  - camelot-py
  - beautifulsoup4
  - pip
  - pypdf
  - requests
  - opencv-python-headless
  - tqdm
